In [23]:
import numpy as np
mask = list(range(10))
mask = np.reshape(mask, (5,2))
mask = np.reshape(mask, (2, -1))
print(mask.shape)
print(np.sum(mask*mask))

(2, 5)
285


In [16]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict["brand"])

Ford


In [33]:
mat1 = list(range(30))
mat1 = np.reshape(mat1, (3,10))
print(mat1)
print(mat1[2])
print(mat1[:,2])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[20 21 22 23 24 25 26 27 28 29]
[ 2 12 22]


In [34]:
N=3
M=4
res = [ [ 0 for i in range(N) ] for j in range(M) ] 
print(res)

[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]


In [97]:
mat1 = list(range(2))
mat1 = np.reshape(mat1, (1,2))
mat2 = list(range(6))
mat2 = np.reshape(mat2, (3,2))
print(mat1)
print(mat2)
print(np.maximum(mat2,2))



[[0 1]]
[[0 1]
 [2 3]
 [4 5]]
[[2 2]
 [2 3]
 [4 5]]


In [89]:
np.arange(3)
print(np.arange(3).shape)

(3,)
