In [1]:
import numpy as np
mask = list(range(10))
mask = np.reshape(mask, (5,2))
mask = np.reshape(mask, (2, -1))
print(mask.shape)
print(np.sum(mask*mask))

(2, 5)
285


In [16]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict["brand"])

Ford


In [33]:
mat1 = list(range(30))
mat1 = np.reshape(mat1, (3,10))
print(mat1)
print(mat1[2])
print(mat1[:,2])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[20 21 22 23 24 25 26 27 28 29]
[ 2 12 22]


In [34]:
N=3
M=4
res = [ [ 0 for i in range(N) ] for j in range(M) ] 
print(res)

[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]


In [18]:
import numpy as np
mat1 = list(range(2))
mat1 = np.reshape(mat1, (1,2))
mat2 = list(range(6))
mat2 = np.reshape(mat2, (3,2))
print(mat1)
print(mat2)
print(np.argmax(mat2,1))

np.sum(mat2, axis=1)[2]

[[0 1]]
[[0 1]
 [2 3]
 [4 5]]
[1 1 1]


9

In [120]:
learning_rates = [1e-7, 1e-6]
regularization_strengths = [2e4, 2.5e4, 3e4, 3.5e4, 4e4, 4.5e4, 5e4, 6e4]
grid_search = [ (lr,rg) for lr in learning_rates for rg in regularization_strengths ]
print(grid_search)

[(1e-07, 20000.0), (1e-07, 25000.0), (1e-07, 30000.0), (1e-07, 35000.0), (1e-07, 40000.0), (1e-07, 45000.0), (1e-07, 50000.0), (1e-07, 60000.0), (1e-06, 20000.0), (1e-06, 25000.0), (1e-06, 30000.0), (1e-06, 35000.0), (1e-06, 40000.0), (1e-06, 45000.0), (1e-06, 50000.0), (1e-06, 60000.0)]


In [9]:
list(range(5,10))

[5, 6, 7, 8, 9]

In [63]:
mat1 = [[1,2],[3,4]]
np.exp(mat1)

mat2=np.reshape(mat1,[2,2])
mat3=np.max(mat2, axis=1)[np.newaxis]
mat3=np.transpose(mat3)
mat2-mat3

array([[-1,  0],
       [-1,  0]])

In [80]:
mat1 = [[1,2],[3,4]]
mat1=np.reshape(mat1,[2,2])
mat2 = np.arange(2)
mat3 = [0,1]

mat4=mat1[mat2,mat3]
mat5=np.sum(mat1, axis=1)
mat4/mat5


array([0.33333333, 0.57142857])

In [3]:
a = np.array([[1,2],[3,4]])
a = a.reshape(2,2)
np.maximum(a,2)

array([[2, 2],
       [3, 4]])